build:
  api:
    docker:
      file: Dockerfile
      tag: ${GIT_COMMIT},${GIT_TAG},latest
      append-cert: false
      args:
        - BUILD_VERSION=${GIT_TAG}
        - BUILD_GIT_COMMIT=${GIT_COMMIT}
        - BUILD_REF=${BUILD_REF}
